#######################################################################################
# Book settings
title:  Calcium Imaging Data Analysis
author: Sayma Nowshin Chowdhury
copyright: "Pessoalab"
logo: "umd logo.jpg"

#######################################################################################
# Execution settings
execute:
  execute_notebooks: off

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar: false
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true

#######################################################################################
# Launch button settings
repository:
  url: https://github.com/saymanowshin/sayma_nowshin
latex:
  latex_engine: "xelatex"
  latex_documents:
    targetname: book.tex

theme: jekyll-theme-cayman
